pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/highway"

train_data:
  video_path: "data/highway.mp4"
  prompt: "a white van drives by a dashcam on a forrested highway"
  n_sample_frames: 24
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  prompts:
    - "a white van drives by a dashcam on an autumn forrested highway"
    - "a Scooby Doo Bus drive by a dashcam on a forrested highway"
    - "a white van drives by a dashcam on a snowy highway"
    - "a blue FordGT drives by a dashcam on a desert highway"
    - "a BMW aggressively cuts off a car on a dashcam on a forrested highway"
  video_length: 24
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 250
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
